---
title: "Visualization"
---

## Instructions


A [helpful video](https://www.dropbox.com/scl/fi/4x2nf8sg7euyjqafzil05/posit-cloud-homework.mov?rlkey=k6kilgrmtudszob7kkc67af10&dl=0) is available to guide you through the process of completing this assignment

1. Download this file: <i class="far fa-file-archive"></i> [`ps-viz.qmd`](../problem-sets/f24/ps-viz.qmd)
    - right-click, "save/download file as..."
2. Upload to Posit Cloud
3. Complete all of the coding tasks, **write down your answers to the questions**, and save the file
4. **Once you are done**, export the `.qmd` file and go on Canvas and answer the questions related to the assignment
5. You will submit your `.qmd` file in the Canvas assignment

## Tips

- Make sure you: 
    - run all of the code chunks that already have code in them
    - write your code in the empty code chunks
- Useful shortcuts: 
    - to run all the code in a specific code chunk, press the green right-facing triangle at the top right of the code chunk
    - to run all *prior* code chunks, press the downward-facing gray triangle at the top right of the code chunk


