---
title: "Models"
---



```{r setup, include=FALSE}
# set knit options
knitr::opts_chunk$set(
  fig.width=9, 
  fig.height=5, 
  fig.retina=3,
  fig.align="center",
  out.width = "100%",
  cache = FALSE,
  echo = TRUE,
  message = FALSE, 
  warning = FALSE
)

# source in functions
source(here::here("R", "funcs.R"))

```




## In-class example


Here's the code we'll be using in class. Download it and store it with the rest of your materials for this course. If simply clicking doesn't trigger download, you should right-click and select "save link as..."

- [<i class="fas fa-file-archive"></i> `05-models.R`](/files/example-scripts/05-models.R)





Load libraries:

```{r}
library(tidyverse)
library(broom)
library(juanr)
library(socviz)
```


## Class: trade


Fit and extract model:

```{r}
# work here
sea_model = lm(exports ~ sea_borders, data = trade)
tidy(sea_model)
```



## Class: socviz


Fit and extract model:

```{r}
# work here
mod_happy = lm(kids ~ happy, data = gss_sm)
tidy(mod_happy)
```
