project:
  type: website
  render:
    - "*.qmd"
    - "!problem-sets/"
  preview:
    port: 27514

execute: 
  freeze: auto

bibliography: files/bib/refs.bib
link-citations: false
csl: files/bib/chicago-syllabus-no-bib.csl

description-meta: "Website for my course on undergraduate research methods."

website:
  title: "The Scientific Study of Politics"
  search: false
  site-url: "https://quantpol.juanftellez.com"

  navbar:
    pinned: true
    right:
      - text: "Syllabus"
        file: index.qmd
      - text: "Schedule"
        file: schedule.qmd
      - text: "Assignments"
        file: assignment/index.qmd
      - text: "Examples"
        file: example/index.qmd
      - text: "Guides"
        file: guides/guides.qmd
      - text: Slack
        icon: slack
        href: "https://pol51f23.slack.com"
        aria-label: Slack

  sidebar: 
  - title: "Guides"
    style: docked
    search: false
    background: dark
    contents:
      - guides/guides.qmd
      - guides/install.qmd
      - guides/reading-data.qmd
      
  - title: "Assignments"
    style: "docked"
    search: false
    background: dark
    contents: 
      - section: "Overview"
        contents:
          - assignment/index.qmd
      - section: "Problem sets"
        contents:
            - assignment/02-assignment.qmd
            - assignment/03-assignment.qmd
            - assignment/04-assignment.qmd
            - assignment/06-assignment.qmd
            - assignment/07-assignment.qmd
            - assignment/08-assignment.qmd
            - assignment/09-assignment.qmd
            - assignment/10-assignment.qmd

  - title: "Content"
    style: "docked"
    search: false
    background: dark
    contents: 
       section: "Class materials"
       contents:
          - content/01-content.qmd
          - content/02-content.qmd
          - content/03-content.qmd
          - content/04-content.qmd
          - content/05-content.qmd
          - content/06-content.qmd
          - content/07-content.qmd
          - content/08-content.qmd
          - content/09-content.qmd
          - content/10-content.qmd
          - content/11-content.qmd
  
  - title: "Examples"
    style: "docked"
    search: false
    background: dark
    contents: 
      - section: "Overview"
        contents:
          - example/index.qmd
      - section: "Code examples"
        contents:
            - example/01-example.qmd
            - example/02-example.qmd
            - example/03-example.qmd
            - example/04-example.qmd
            - example/06-example.qmd
            - example/07-example.qmd
            - example/08-example.qmd
            - example/09-example.qmd
            - example/10-example.qmd       

  page-footer:
    left: |
      Content {{< fa copyright >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme: html/custom.scss
    anchor-sections: false
    toc: true
    css: html/tenso-berkeley.css
    highlight-style: monokai
