---
title: "Uncertainty"
---


```{r slides, echo=FALSE, include=FALSE}
source(here::here("R", "slide-things.R"))

slide_details = tibble::tribble(
  ~youtube_id,   ~title, ~slide, ~active,
  "", "", "1", TRUE)

```

## Optional

- {{< fa book >}} Chapter 7 from [ModernDive](https://moderndive.com/7-sampling.html)


## Slides


### Day one

```{r, echo=FALSE, results="asis", eval = TRUE}
slide_buttons("/slides/f24/16-uncertainty")
```

<!-- ### Tuesday -->


<!-- ```{r, echo=FALSE, results="asis", eval = TRUE} -->
<!-- slide_buttons("/slides/16-uncertainty") -->
<!-- ``` -->

<!-- ```{=html} -->
<!-- <iframe width="780" height="500" src="/slides/16-uncertainty.html"></iframe> -->
<!-- ``` -->


<!-- ### Thursday -->


<!-- ```{r, echo=FALSE, results="asis", eval = TRUE} -->
<!-- slide_buttons("/slides/17-uncertainty") -->
<!-- ``` -->

<!-- ```{=html} -->
<!-- <iframe width="780" height="500" src="/slides/17-uncertainty.html"></iframe> -->
<!-- ``` -->

<!-- ::: {.callout-note} -->
<!-- You can navigate through the slides with <kbd>←</kbd> and <kbd>→</kbd>. If you type <kbd>F</kbd> you can go full-screen.  -->
<!-- ::: -->



